[package]
name = "query"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
chunk = { path = "../chunk" }
resource = { path = "../resource" }
executor = { path = "../executor" }
promql = "0.4"
thiserror = "1"
async-channel = "1"
hashbrown = "0.13"
