[package]
name = "resource"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror.workspace = true
chunk = { path = "../chunk" }
common = { path = "../common" }
executor = { path = "../executor" }
croaring = "0.8"
hashbrown.workspace = true
