[package]
name = "chunk"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
croaring = "0.8"
hashbrown.workspace = true
pdatastructs = "0.7"
thiserror.workspace = true
paste.workspace = true
regex.workspace = true

[dev-dependencies]
futures-lite = "1"
