[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
executor = { path = "../executor" }
ahash = "0.8"
hashbrown = "0.13"
thiserror = "1"
